hydra:
    run:
        dir: ./results/${now:%Y-%m-%d}/${now:%H-%M-%S}
# Env config
alg_name: mbme
seed: 0
env_name: anttrap
episode_length: 250
policy_hidden_layer_sizes: [64, 64]
# ME config
num_evaluations: 1000000
batch_size: 32
single_init_state: True
discard_dead: False
#Emitter config
iso_sigma: 0.01
line_sigma: 0.1
crossover_percentage: 1.0
# Grid config
grid_shape: [50, 50]
# Log config
log_period: 50
store_repertoire: True
store_repertoire_log_period: 200
plot_grid: False
plot_grid_log_period: 200

# Surrogate Model Parameters
num_imagined_iterations: 100
add_buffer_size: 512 # at the moment needs to be the same as batchsize
# model parameters
surrogate_hidden_layer_sizes: [512, 512]
surrogate_ensemble_size: 4
# model training parameters
surrogate_learning_rate: 0.001
surrogate_batch_size: 32
num_model_training_steps: 2000
surrogate_replay_buffer_size: 4000000
surrogate_model_update_period: 25 # how often to update the model
max_epochs_since_improvement: 10

prob: False # use probablistic model (predict distirbution)
learn_std: False # learn std of the probalistic model
fixed_std: 0.01 # if learn_std is false, use fixed std
ts_inf: True # how to use ensemble for predictions. False will be ts_1 for use of ensemble

use_grad_clipping: True
grad_clip_value: 1000.0

num_batches_per_loss: 10

learn_rwd: False
